### ISSUE TITLE
Add Link to Slack channel

### ISSUE THREAD

**Issue by niccokunzmann** [OpnTec/2017.opentechsummit.de#1]
We have an open channel where we can discuss the event: https://opntecorg.herokuapp.com/

This should be on the page, so people can join and ask questions.

**Comment by shikhar-scs** [comment]
If this issue is still up can I work on it ??
@niccokunzmann @mariobehling

**Comment by niccokunzmann** [comment]
Hi:)

If you like, you can do so.
I do not think it is fixed.

**Comment by shikhar-scs** [comment]
@niccokunzmann Sure I'm on it. Is there any specific place where I should add this link [https://opntecorg.herokuapp.com/](https://opntecorg.herokuapp.com/) OR should I add somewhere towards the end?

**Comment by niccokunzmann** [comment]
I think, It would be good somewhere where people want to get in touch..
e.g. near social media.
But I do not have an exact place. I think, you will find one where you
think it is best.

**Comment by shikhar-scs** [comment]
Yeah no problem @niccokunzmann I'll take care of that.

**Comment by shikhar-scs** [comment]
@niccokunzmann I have made the required changes and also opened a PR. Please review.

**Comment by niccokunzmann** [comment]
Thanks @shikhar-scs! I will close the issue since it is solved in #11.

**Comment by shikhar-scs** [comment]
Thanx a lot @niccokunzmann :+1:
