### ISSUE TITLE
Add new LPI logo to website

### ISSUE THREAD

**Issue by mariobehling** [OpnTec/2017.opentechsummit.de#4]
[LPI_Logo-Web_Colour.eps.zip](https://github.com/OpnTec/2017.opentechsummit.net/files/784720/LPI_Logo-Web_Colour.eps.zip)

**Comment by shikhar-scs** [comment]
@mariobehling @niccokunzmann 

I would like to work on this issue. Could you please be a bit more precise as to where exactly I need to display this logo on the website [https://2017.opentechsummit.net/](https://2017.opentechsummit.net/)

My best shot would be to the extreme right of the navbar maybe

**Comment by niccokunzmann** [comment]
Please have a look at almost the bottom: "Veranstaltungspartner" it says. Maybe it was already added.

**Comment by shikhar-scs** [comment]
@niccokunzmann Yeah I noticed it right now, and it has a dark reddish tint. I'll update it with the yellow one provided above ASAP and file a PR.
